env:
  node: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  import/no-named-as-default: 0
  import/no-named-as-default-member: 0