env:
  browser: true
  es2020: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  import/extensions: 0
  no-console: 0
  no-unused-expressions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/no-named-as-default: 0
  import/no-named-as-default-member: 0
  fp/no-mutating-methods: 0
  