plugins:
  - jest

env:
  node: true
  es2021: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  import/no-named-as-default: 0
  import/no-named-as-default-member: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]