name: myactionbuild
on:
  - push
  - pull_request
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install-deps
        run: make install-deps
      - name: run linter
        run: make lint
      - name: run tests
        run: make test
      - name: Test & publish code coverage
       # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v3.0.0 
         # Add Code Climate secret key
        env:
           CC_TEST_REPORTER_ID: ${{ secrets.TESTCOVERAGE }}
        with:
           coverageCommand: make test-coverage
           debug: true
